# Generated by Django 2.1 on 2018-10-31 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recyclable',
            fields=[
                ('item', models.CharField(blank=True, default='', max_length=100)),
                ('methods', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
